version: 0.0
os: linux 
files:
  - source: /
    destination: /home/ubuntu
    #overwrite: true
hooks:
  ApplicationStop:
    - location: scripts/application_stop.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 300
      runas: ubuntu


#!/bin/bash
cd /home/ubuntu
sudo pm2 start /home/ubuntu/app.js




#!/bin/bash
cd /home/ubuntu
sudo pm2 stop /home/ubuntu/app.js
